package com.ninecsdev.wallpaperchanger.data.local

import android.net.Uri
import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.MapColumn
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import com.ninecsdev.wallpaperchanger.model.enums.CropRule
import com.ninecsdev.wallpaperchanger.model.CollectionRotationSetting
import com.ninecsdev.wallpaperchanger.model.enums.SourceType
import com.ninecsdev.wallpaperchanger.model.FolderExclusion
import com.ninecsdev.wallpaperchanger.model.Wallpaper
import com.ninecsdev.wallpaperchanger.model.WallpaperCollection
import com.ninecsdev.wallpaperchanger.model.WallpaperFile
import com.ninecsdev.wallpaperchanger.model.WallpaperImage
import kotlinx.coroutines.flow.Flow

/**
 * Shared projection producing the denormalized [WallpaperImage] read model: the join row plus the
 * referenced file's uri/sourceType/isAvailable. Every query returning [WallpaperImage] builds on
 * this so the column list can't drift between them.
 */
private const val SELECT_WALLPAPER_IMAGES = """
    SELECT w.id, w.collectionId, w.fileId, f.uri, f.sourceType, f.isAvailable,
           w.editZoom, w.editOffsetX, w.editOffsetY, w.isManuallyAdded, w.addedAt, w.isDefault
    FROM wallpapers w JOIN wallpaper_files f ON w.fileId = f.id
"""

/**
 * How many values one `IN (...)` statement is given. SQLite caps the bind variables a single
 * statement may carry, so a query over a caller-sized list is split into runs of this length. Each
 * method that needs the split owns it and runs its statements in one transaction, so the length of
 * a caller's list is never that caller's problem.
 *
 * Deliberately well under the cap (32766) so this could be raised.
 */
private const val BIND_CHUNK_SIZE = 900

/**
 * Data Access Object for Wallpaper and Collection operations.
 */
@Dao
abstract class WallpaperDao {

    // Collection CRUD and operations

    // Ids are autogenerated, so a conflict means a caller invented an id that already exists: fail loudly rather than replace
    @Insert(onConflict = OnConflictStrategy.ABORT)
    abstract suspend fun insertCollection(collection: WallpaperCollection): Long

    @Query("SELECT * FROM collections WHERE isDefaults = 0 ORDER BY lastUsedAt DESC")
    abstract fun observeAllCollections(): Flow<List<WallpaperCollection>>

    @Query("SELECT * FROM collections WHERE id = :collectionId LIMIT 1")
    abstract suspend fun getCollectionById(collectionId: Long): WallpaperCollection?

    @Query("SELECT * FROM collections WHERE isActive = 1 LIMIT 1")
    abstract suspend fun getActiveCollection(): WallpaperCollection?

    /** Flow sibling of [getActiveCollection]; re-emits whenever the active collection changes. */
    @Query("SELECT * FROM collections WHERE isActive = 1 LIMIT 1")
    abstract fun observeActiveCollection(): Flow<WallpaperCollection?>

    /**
     * How many collections are backed by the folder [rootUri]. Guards the persisted-grant release:
     * two collections built from the same folder share one grant, so it may only be released when
     * this reaches zero.
     */
    @Query("SELECT COUNT(*) FROM collections WHERE rootUri = :rootUri")
    abstract suspend fun countCollectionsWithRootUri(rootUri: Uri): Int

    /** All folder root uris across collections (manual collections' null roots excluded). */
    @Query("SELECT rootUri FROM collections WHERE rootUri IS NOT NULL")
    abstract suspend fun getAllRootUris(): List<Uri>

    /** The app-owned Favourites collection, or null if it hasn't been created yet. */
    @Query("SELECT * FROM collections WHERE isFavorites = 1 LIMIT 1")
    abstract suspend fun getFavoritesCollection(): WallpaperCollection?

    /** The app-owned collection holding default wallpapers, or null if it hasn't been created yet. */
    @Query("SELECT * FROM collections WHERE isDefaults = 1 LIMIT 1")
    abstract suspend fun getDefaultsCollection(): WallpaperCollection?

    /** Updates the name, default crop rule and rotation setting of a collection. */
    @Query("UPDATE collections SET name = :newName, defaultCropRule = :newRule, rotationPolicy = :newPolicy WHERE id = :collectionId")
    abstract suspend fun updateCollection(
        collectionId: Long,
        newName: String,
        newRule: CropRule,
        newPolicy: CollectionRotationSetting
    )

    /** Toggles the active collection atomically and zeroes last rotation time*/
    // TODO tests: see vault note tests/Collection Switch Rotation Gate Tests.md
    @Transaction
    open suspend fun setActiveCollection(collectionId: Long) {
        resetActiveCollection()
        markCollectionActive(collectionId)
        updateLastUsed(collectionId)
        updateLastWallpaperChangeAt(collectionId, 0L)
    }

    /** Sets the user-controlled pin flag (pinned collections sort first in every collection grid). */
    @Query("UPDATE collections SET isPinned = :pinned WHERE id = :collectionId")
    abstract suspend fun setCollectionPinned(collectionId: Long, pinned: Boolean)

    @Query("UPDATE collections SET lastWallpaperChangeAt = :timestamp WHERE id = :collectionId")
    abstract suspend fun updateLastWallpaperChangeAt(collectionId: Long, timestamp: Long = System.currentTimeMillis())

    @Delete
    abstract suspend fun deleteCollection(collection: WallpaperCollection)

    // Helper functions for setActiveCollection()
    @Query("UPDATE collections SET isActive = 0")
    abstract suspend fun resetActiveCollection()

    @Query("UPDATE collections SET isActive = 1 WHERE id = :collectionId")
    abstract suspend fun markCollectionActive(collectionId: Long)

    @Query("UPDATE collections SET lastUsedAt = :timestamp WHERE id = :collectionId")
    abstract suspend fun updateLastUsed(collectionId: Long, timestamp: Long = System.currentTimeMillis())

    // File registry (wallpaper_files) CRUD

    /** Inserts a file row. `uri` is unique; on conflict returns -1 (use [getOrCreateFile]). */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    abstract suspend fun insertFile(file: WallpaperFile): Long

    @Query("SELECT * FROM wallpaper_files WHERE uri = :uri LIMIT 1")
    abstract suspend fun getFileByUri(uri: Uri): WallpaperFile?

    /**
     * Returns the id of the file row for [uri], creating it if absent. Dedups shared images so the
     * same photo added to several collections is stored once.
     *
     * A reused row is also restored to available: reaching this point means the source was just
     * proven readable (picker probe passed / folder scan listed it), so a stale self-heal flag
     * must not keep excluding it from rotation.
     */
    @Transaction
    open suspend fun getOrCreateFile(uri: Uri, sourceType: SourceType, addedAt: Long): Long {
        val inserted = insertFile(WallpaperFile(uri = uri, sourceType = sourceType, addedAt = addedAt))
        if (inserted != -1L) return inserted
        val existing = getFileByUri(uri)!!
        if (!existing.isAvailable) setFileAvailability(existing.id, true)
        return existing.id
    }

    /** File rows referenced by no join row. */
    @Query("SELECT * FROM wallpaper_files WHERE id NOT IN (SELECT DISTINCT fileId FROM wallpapers)")
    abstract suspend fun getOrphanFiles(): List<WallpaperFile>

    /** All uris of the given source type. */
    @Query("SELECT uri FROM wallpaper_files WHERE sourceType = :type")
    abstract suspend fun getFileUrisBySourceType(type: SourceType): List<Uri>

    /** All file rows of the given source type. */
    @Query("SELECT * FROM wallpaper_files WHERE sourceType = :type")
    abstract suspend fun getFilesBySourceType(type: SourceType): List<WallpaperFile>

    /** Reactive count of files of the given source type. Drives the main screen's "photo access revoked" banner. */
    @Query("SELECT COUNT(*) FROM wallpaper_files WHERE sourceType = :type")
    abstract fun observeFileCountBySourceType(type: SourceType): Flow<Int>

    /** Toggles a file's availability. */
    @Query("UPDATE wallpaper_files SET isAvailable = :available WHERE id = :fileId")
    abstract suspend fun setFileAvailability(fileId: Long, available: Boolean)

    /** Bulk sibling of [setFileAvailability]. [fileIds] may be of any length. */
    @Transaction
    open suspend fun setFilesAvailability(fileIds: List<Long>, available: Boolean) {
        fileIds.chunked(BIND_CHUNK_SIZE).forEach { setFilesAvailabilityChunk(it, available) }
    }

    @Query("UPDATE wallpaper_files SET isAvailable = :available WHERE id IN (:fileIds)")
    protected abstract suspend fun setFilesAvailabilityChunk(fileIds: List<Long>, available: Boolean)

    /**
     * Repoints a file row to a freshly picked source and restores it to available. Used to re-link
     * an unavailable image keeping its edit params.
     *
     * Note: Caller must guarantee [uri] isn't already held by a different file row (uri is unique).
     */
    @Query("UPDATE wallpaper_files SET uri = :uri, sourceType = :sourceType, isAvailable = 1 WHERE id = :fileId")
    abstract suspend fun rebindFile(fileId: Long, uri: Uri, sourceType: SourceType)

    /**
     * Merge step for re-link when the picked uri already exists as a different file row: drops the
     * old file's join rows for collections that already reference [newFileId], so the subsequent
     * [repointJoinRows] can't violate the unique (collectionId, fileId) index. The pre-existing
     * membership wins; the unavailable duplicate is discarded.
     */
    @Query("DELETE FROM wallpapers WHERE fileId = :oldFileId AND collectionId IN (SELECT collectionId FROM wallpapers WHERE fileId = :newFileId)")
    abstract suspend fun deleteJoinRowsDuplicatedByMerge(oldFileId: Long, newFileId: Long)

    /** Merge step for re-link: moves the old file's remaining join rows onto the existing file row. */
    @Query("UPDATE wallpapers SET fileId = :newFileId WHERE fileId = :oldFileId")
    abstract suspend fun repointJoinRows(oldFileId: Long, newFileId: Long)

    /** Deletes the given file rows. [ids] may be of any length. */
    @Transaction
    open suspend fun deleteFilesByIds(ids: List<Long>) {
        ids.chunked(BIND_CHUNK_SIZE).forEach { deleteFilesByIdsChunk(it) }
    }

    @Query("DELETE FROM wallpaper_files WHERE id IN (:ids)")
    protected abstract suspend fun deleteFilesByIdsChunk(ids: List<Long>)

    // Wallpaper (join) CRUD and operations

    /** Inserts join rows; duplicates are ignored via the unique index. */
    // An insert binds one row at a time, so the per-statement cap behind BIND_CHUNK_SIZE does not reach this path.
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    abstract suspend fun insertWallpapers(wallpapers: List<Wallpaper>)

    /** Flow of images for a collection, sorted newest-first (used in UI). */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.collectionId = :collectionId AND w.isDefault = 0 ORDER BY w.addedAt DESC")
    abstract fun observeImagesForCollection(collectionId: Long): Flow<List<WallpaperImage>>

    /**
     * Every collection's newest [limit] thumbnail uris, keyed by collection.
     *
     * `ROW_NUMBER()` numbers each collection's rows independently, so the outer `rn <= :limit`
     * takes a per-collection top-N without a query per collection. The outer `ORDER BY` puts each
     * collection's uris into the map's list in rank order.
     *
     * A collection with no images is absent from the map.
     */
    // TODO tests: see vault note tests/Collection Picker Tests.md
    @Query(
        """
        SELECT collectionId, uri FROM (
            SELECT w.collectionId AS collectionId, f.uri AS uri,
                   ROW_NUMBER() OVER (
                       PARTITION BY w.collectionId ORDER BY w.addedAt DESC, w.id ASC
                   ) AS rn
            FROM wallpapers w JOIN wallpaper_files f ON w.fileId = f.id
            WHERE w.isDefault = 0
        )
        WHERE rn <= :limit
        ORDER BY collectionId, rn
        """
    )
    abstract fun observePreviewUrisByCollection(limit: Int): Flow<Map<@MapColumn("collectionId") Long, List<@MapColumn("uri") Uri>>>

    /** Every collection's image count, keyed by collection. Collections with no images are absent from the map as in [observePreviewUrisByCollection] */
    @Query("SELECT collectionId, COUNT(*) AS imageCount FROM wallpapers WHERE isDefault = 0 GROUP BY collectionId")
    abstract fun observeImageCountsByCollection(): Flow<Map<@MapColumn("collectionId") Long, @MapColumn("imageCount") Int>>

    /**
     * Reactive sibling of [observeImagesForCollection] that excludes files marked unavailable.
     * Used exclusively by [RotationEngine][com.ninecsdev.wallpaperchanger.logic.RotationEngine]'s
     * magazine so self-heal never selects a source that's already known to be unreadable.
     */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.collectionId = :collectionId AND w.isDefault = 0 AND f.isAvailable = 1")
    abstract fun observeAvailableImagesForCollection(collectionId: Long): Flow<List<WallpaperImage>>

    /**
     * Wallpapers in [collectionId] whose backing file is marked unavailable — candidates for a
     * re-probe (collection screen open, folder sync) that may clear the flag if readable again.
     */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.collectionId = :collectionId AND f.isAvailable = 0")
    abstract suspend fun getUnavailableImagesForCollection(collectionId: Long): List<WallpaperImage>

    /**
     * Returns only the folder-sourced images for a collection ([SourceType.FOLDER_DOC]).
     * Used during folder sync to compute diffs without touching manually added/re-linked images
     */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.collectionId = :collectionId AND w.isManuallyAdded = 0 AND f.sourceType = :sourceType")
    abstract suspend fun getFolderImagesForCollection(
        collectionId: Long,
        sourceType: SourceType = SourceType.FOLDER_DOC
    ): List<WallpaperImage>

    /**
     * Join rows in [collectionId] whose file is one of [fileIds]. Used by cross-collection
     * transfers to detect duplicates (the target already has the file) before inserting.
     * [fileIds] may be of any length.
     */
    @Transaction
    open suspend fun getWallpapersInCollectionForFiles(
        collectionId: Long,
        fileIds: List<Long>
    ): List<Wallpaper> =
        fileIds.chunked(BIND_CHUNK_SIZE).flatMap { getWallpapersInCollectionForFilesChunk(collectionId, it) }

    @Query("SELECT * FROM wallpapers WHERE collectionId = :collectionId AND isDefault = 0 AND fileId IN (:fileIds)")
    protected abstract suspend fun getWallpapersInCollectionForFilesChunk(
        collectionId: Long,
        fileIds: List<Long>
    ): List<Wallpaper>

    /** Fetches a single wallpaper by ID. */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.id = :wallpaperId LIMIT 1")
    abstract suspend fun getWallpaperById(wallpaperId: Long): WallpaperImage?

    /** Persists the edit parameters for a wallpaper. */
    @Query("""
        UPDATE wallpapers
        SET editZoom = :zoom, editOffsetX = :offsetX, editOffsetY = :offsetY
        WHERE id = :wallpaperId
    """)
    abstract suspend fun updateWallpaperEdit(
        wallpaperId: Long,
        zoom: Float?,
        offsetX: Float?,
        offsetY: Float?
    )

    /** Deletes the given join rows. [ids] may be of any length. */
    @Transaction
    open suspend fun deleteImagesByIds(ids: List<Long>) {
        ids.chunked(BIND_CHUNK_SIZE).forEach { deleteImagesByIdsChunk(it) }
    }

    @Query("DELETE FROM wallpapers WHERE id IN (:ids)")
    protected abstract suspend fun deleteImagesByIdsChunk(ids: List<Long>)

    // Default wallpapers (one flagged membership per collection)
    // TODO tests: see vault note tests/Default Wallpaper Membership Tests.md (exclusion)

    /** The default wallpaper of [collectionId], or null if it has none. */
    @Query("$SELECT_WALLPAPER_IMAGES WHERE w.collectionId = :collectionId AND w.isDefault = 1 LIMIT 1")
    abstract suspend fun getDefaultWallpaper(collectionId: Long): WallpaperImage?

    /** The global default wallpaper: the default row of the app-owned defaults collection. */
    @Query("$SELECT_WALLPAPER_IMAGES JOIN collections c ON w.collectionId = c.id WHERE c.isDefaults = 1 AND w.isDefault = 1 LIMIT 1")
    abstract fun observeGlobalDefaultWallpaper(): Flow<WallpaperImage?>

    /** Repoints a default row at a freshly picked file, dropping the edit that framed the old one. */
    @Query("UPDATE wallpapers SET fileId = :fileId, editZoom = NULL, editOffsetX = NULL, editOffsetY = NULL WHERE id = :wallpaperId")
    abstract suspend fun repointDefaultWallpaper(wallpaperId: Long, fileId: Long)

    /**
     * Uris of the files referenced *only* by default rows. The storage readout subtracts these:
     * defaults are internalized whatever the user's "keep local copies" setting says, so their
     * bytes are not a cost of that setting.
     */
    @Query("""
        SELECT f.uri FROM wallpaper_files f
        WHERE f.id IN (SELECT fileId FROM wallpapers WHERE isDefault = 1)
          AND f.id NOT IN (SELECT fileId FROM wallpapers WHERE isDefault = 0)
    """)
    abstract suspend fun getDefaultOnlyFileUris(): List<Uri>

    // Favourites (memberships of the system collection, keyed by fileId)

    /** Reactive set of file ids that have a membership in the Favourites collection. */
    @Query("SELECT DISTINCT w.fileId FROM wallpapers w JOIN collections c ON w.collectionId = c.id WHERE c.isFavorites = 1 AND w.isDefault = 0")
    abstract fun observeFavoriteFileIds(): Flow<List<Long>>

    /** Removes the Favourites membership (unfavourite) for the given files. [fileIds] may be of any length. */
    @Transaction
    open suspend fun deleteJoinRowsForFiles(collectionId: Long, fileIds: List<Long>) {
        fileIds.chunked(BIND_CHUNK_SIZE).forEach { deleteJoinRowsForFilesChunk(collectionId, it) }
    }

    @Query("DELETE FROM wallpapers WHERE collectionId = :collectionId AND fileId IN (:fileIds)")
    protected abstract suspend fun deleteJoinRowsForFilesChunk(collectionId: Long, fileIds: List<Long>)

    // Folder exclusions

    /**
     * Inserts exclusion tombstones. IGNORE keeps the *older* row on a (collectionId, uri) conflict:
     * an already-excluded uri can't be a member (invariant).
     */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    abstract suspend fun insertExclusions(exclusions: List<FolderExclusion>)

    /** All exclusion tombstones of a collection (sync reads these to filter re-adds). */
    @Query("SELECT * FROM folder_exclusions WHERE collectionId = :collectionId")
    abstract suspend fun getExclusionsForCollection(collectionId: Long): List<FolderExclusion>

    /** Reactive exclusion count; drives the "Restore removed images (N)" row in the edit card. */
    @Query("SELECT COUNT(*) FROM folder_exclusions WHERE collectionId = :collectionId")
    abstract fun observeExclusionCount(collectionId: Long): Flow<Int>

    /** Wipes every exclusion of a collection (the "Restore removed images" bulk action). */
    @Query("DELETE FROM folder_exclusions WHERE collectionId = :collectionId")
    abstract suspend fun deleteExclusionsForCollection(collectionId: Long)

    /**
     * Clears exclusions matching the given uris, the add-path half of the invariant that a uri is
     * never both excluded from and a member of the same collection. [uris] may be of any length.
     */
    @Transaction
    open suspend fun deleteExclusionsForUris(collectionId: Long, uris: List<Uri>) {
        uris.chunked(BIND_CHUNK_SIZE).forEach { deleteExclusionsForUrisChunk(collectionId, it) }
    }

    @Query("DELETE FROM folder_exclusions WHERE collectionId = :collectionId AND uri IN (:uris)")
    protected abstract suspend fun deleteExclusionsForUrisChunk(collectionId: Long, uris: List<Uri>)

}
